version: "3.8"
services:
  web:
    build:
      context: .
      target: ${ENV}
    ports:
      - "8000:8000"
    volumes:
      - ./build/index.js:/app/index.js
      - ./build/test.js:/app/test.js
      - ./build/package.json:/app/package.json
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
